services:
  cassandra:
    image: cassandra:4
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      # - CASSANDRA_CLUSTER_NAME=TestCluster
      # - CASSANDRA_DC=datacenter1
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_RACK=location
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ./infra/db/cassandra/data.cql:/data.cql
      - ./infra/db/cassandra/init.sh:/init.sh
    command: /init.sh
    networks:
      - application

  servergolang1: &servergo
    build:
      context: ./server
    container_name: servergolang1
    restart: unless-stopped
    ports:
      - "4243:4242"
    environment:
      - CASSANDRA_URL=cassandra:9042
      - CASSANDRA_KEYSPACE=projeto
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - cassandra
    networks:
      - application

  servergolang2:
    <<: *servergo
    container_name: servergolang2
    restart: unless-stopped
    ports:
      - "4244:4242"
    environment:
      - CASSANDRA_URL=cassandra:9042
      - CASSANDRA_KEYSPACE=projeto
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - cassandra
    networks:
      - application

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - servergolang1
      - servergolang2
    networks:
      - application

  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./infra/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - application
      - monitoring

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 256M
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - ./infra/monitoring/grafana-data:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  application:
  monitoring:
