version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=iago
      - POSTGRES_USER=iago
      - POSTGRES_DB=trafego
    ports:
      - "5432:5432"
    volumes:
      - ./infra/boot.sql:/docker-entrypoint-initdb.d/boot.sql
      - ./infra/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iago -d trafego"]
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1GB"
    networks:
      - project-net

  backend1:
    build:
      context: ./backend
    container_name: backend1
    ports:
      - "4242:4242"
    environment:
      - DATABASE_URL=postgresql://iago:iago@db:5432/trafego
    depends_on:
      - db
    networks:
      - project-net

  backend2:
    build:
      context: ./backend
    container_name: backend2
    ports:
      - "4243:4242"
    environment:
      - DATABASE_URL=postgresql://iago:iago@db:5432/trafego
    depends_on:
      - db
    networks:
      - project-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
    networks:
      - project-net

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    networks:
      - project-net

  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    ports:
      - "3003:3003"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
      - db
      - prometheus
    volumes:
      - ./infra/grafana-data:/var/lib/grafana
    networks:
      - project-net

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://iago:iago@db:5432/trafego?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - project-net
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - project-net
    depends_on:
      - postgres_exporter

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
    networks:
      - project-net

volumes:
  postgres-data:
  grafana-data:

networks:
  project-net:
