version: "3.5"

services:
  db:
    image: postgres:16.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=iago
      - POSTGRES_USER=iago
      - POSTGRES_DB=trafego
    ports:
      - "5432:5432"
    volumes:
      - ./infra/boot.sql:/docker-entrypoint-initdb.d/boot.sql
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U iago -d trafego"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.53"
    #       memory: "200MB"

volumes:
  postgres_data:
    driver: local
