services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    networks:
      - grafana-net

  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
      - db
      - prometheus
    volumes:
      - ./infra/grafana-data:/var/lib/grafana
    networks:
      - grafana-net

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=iago
      - POSTGRES_USER=iago
      - POSTGRES_DB=trafego
    ports:
      - "5432:5432"
    volumes:
      - ./infra/boot.sql:/docker-entrypoint-initdb.d/boot.sql
      - ./infra/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iago -d trafego"]
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1GB"
    networks:
      - grafana-net

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://iago:iago@db:5432/trafego?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - grafana-net
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - grafana-net
    depends_on:
      - postgres_exporter

volumes:
  postgres-data:
  grafana-data:

networks:
  grafana-net:
