version: "3.5"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb

  db:
    image: postgres:16.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=iago
      - POSTGRES_USER=iago
      - POSTGRES_DB=trafego
    ports:
      - "5432:5432"
    volumes:
      - ./infra/boot.sql:/docker-entrypoint-initdb.d/boot.sql
      - ./infra/postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U iago -d trafego"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1GB"

volumes:
  postgres_data:
