services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=iago
      - POSTGRES_USER=iago
      - POSTGRES_DB=trafego
    ports:
      - "5432:5432"
    volumes:
      - ./infra/db/boot.sql:/docker-entrypoint-initdb.d/boot.sql
      - ./infra/db/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iago -d trafego"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - application

  backend1: &backend
    build:
      context: ./backend
    container_name: backend1
    ports:
      - "4240:4242"
    environment:
      - DATABASE_URL=postgresql://iago:iago@db:5432/trafego
    depends_on:
      - db
    networks:
      - application

  backend2:
    <<: *backend
    container_name: backend2
    ports:
      - "4241:4242"
    environment:
      - DATABASE_URL=postgresql://iago:iago@db:5432/trafego
    depends_on:
      - db
    networks:
      - application

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend1
      - backend2
    networks:
      - application

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
    networks:
      - application

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - ./infra/monitoring/grafana-data:/var/lib/grafana
    networks:
      - monitoring

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://iago:iago@db:5432/trafego?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - monitoring
      - application
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - postgres_exporter

volumes:
  postgres-data:
  grafana-data:

networks:
  application:
    driver: bridge
  monitoring:
    driver: bridge
