services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopeed
    ports:
      - "5432:5432"
    volumes:
      - ./boot.sql:/docker-entrypoint-initdb.d/boot.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iago -d Projeto"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: 512M

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
