global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "node"
    static_configs:
      - targets:
          - "node_exporter:9100"
          - "172.31.37.210:9100"
          - "172.31.43.12:9100"
          - "172.31.29.39:9100"
          - "172.31.32.56:9100"
          - "172.31.47.213:9100"
