global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "node"
    static_configs:
      - targets:
          - "node_exporter:9100"
          - "172.31.42.141:9100"
          - "172.31.37.239:9100"
