services:
  servernode:
    image: iagoabner/nodejs:latest
    container_name: servernode
    restart: unless-stopped
    ports:
      - "4242:4242"
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 256M
