---
- name: copy folder
  copy:
    src: "files"
    dest: "/home/ec2-user"

- name: Create container
  become: true
  become_user: ec2-user
  shell: "docker compose -f /home/ec2-user/files/docker-compose.yaml up -d"
