---
- name: Create Docker CLI plugins directory
  file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    state: directory
    mode: "0755"

- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.29.0/docker-compose-linux-x86_64"
    dest: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    mode: "0755"

- name: Ensure Docker Compose is executable
  file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    mode: "0755"
    state: file
