services:
  cassandra:
    image: cassandra:4
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    env_file:
      - ./.env
    volumes:
      - ./data.cql:/data.cql
      - ./init.sh:/init.sh
    command: /init.sh

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
