services:
  servernode:
    image: iagoabner/nodejs-queue:latest
    container_name: servernode-queue
    restart: unless-stopped
    ports:
      - "4242:4242"
    env_file:
      - ./.env

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
